travis:
  secure:
    BINSTAR_TOKEN: s/8BEdIyIW0HfE7JHn7h3WP1ExdDV5sZCtq8+qwNxAO/Ek62XNGL6aHlPuVnb48j92YJO3v4CphfftZSIJ1jlsTA3cfS9YSQE7GodL808EGXe+xfF+GefEWususYYpQEuUhXkPXrIy9XULrx1/N+EFe7lv+sCHqVLMjm0Q6bC1qNiyewgHgjuiLdtDOb1JcpQW9fNSWTJDMINldJ16y1tfjZszixX/WYfQ8tEJTKkgcZUyRBL9cWW5HTmRnLSJjBmkxqhlgFw+z7BpnOyeAL5dlHCkU9XAw6taspOoTu5ARoKSfeC2L52wEoeOnoOkc8SivnJjHg8YzYJtUrE2dUjdj+ZzDfApdceDXFZh4hVpLUrYP60MofSlFNToB87mhSf/1lChHWyxvbTSFW1/iSp2BsRJ5v/tFid579zAhRCgQB5Ri22E8qc7qpiRQTwFPj/fQ2MzB2scVM1hUO2TIYEp4S5N3Ege8aqhvS4yTod3aDcfXMCHzGPISn5qsa6j/XskiI1ZCkmIMqtKngkhljvFLCKn4qwe3b0xQU1CLtQH6Aa0pdh2ndRmAbWsbuFg4UiJv5fTwG42cV3iZtBHkqwL8l2JmZvBXeGLUmCG7b9iMDYBkwWa6cUgUEBTocW+rS0trbyDkGIxVIs+mniqCalmLYoaG+CaYpa+i/H63TRHU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
